name: Update Fishing Report

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install node-fetch@2

      - name: Fetch and Build HTML
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: node fetch-and-build.js

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Update fishing report" || echo "No changes"
          git push